{% set name = "parallel" %}
{% set version = "1.20.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: af85cd3bff706ac590ad4e9b7a847abdba2d1426d8eec26d4857e557631b91f1

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/MIT-LICENSE.txt
  summary: Run any kind of code in parallel processes

  dev_url: https://github.com/grosser/{{ name }}

extra:
  recipe-maintainers:
    - sodre
