{% set name = "parallel" %}
{% set version = "1.19.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: c27ee2925978e8100f49063fd60f625522a6e96b08541ac26e7f2a72d594518a

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/MIT-LICENSE.txt
  summary: Run any kind of code in parallel processes

  dev_url: https://github.com/grosser/{{ name }}

extra:
  recipe-maintainers:
    - sodre
