travis:
  secure:
    BINSTAR_TOKEN: 4DoJk1WvxHHX50zMBeEzjrMuoiFLxFBPBeKze5HjHsn+bmem0SO4NbmTElEBdFMdd168Df6lPzr4mBeNiZlTTXRPyWyDku6aZ7LSK5k6fD7A2o6ZGFWfQYmuUadWYcEzPiUl9+OyJ4YRC0TQfGuWtJymCeu+ZCKQ46M/3EQcO8tgPcSf6e3polHo9hSyzigJMIPLchiwnL1redPGW4A3SiBp0CO4k6CiTzLSlxB0VIjhndzK8YCt1fv/CkVArK7I43DnicTYBZ0ypV0xn6LqAS1juyFnYKy1UW2UMYhvWRg+Ain/surmpoZZ++j+SdoXOhPSzsvV0H5i6VBkXoIj/suphlCQ8B/ffvx8IjCH8P7k+U47CSMMt46yGt8twqT98m+MFrBtBMzMGcrNVqOcd5ON0ND7HFXGGv9jrcJD08gPORsASi6e4it9ci67PIooBgz+GYtkyRKy52OVsmOSVCMT7HAOILzTwStSXcyXWImUdp4MdHAkdUIH9rAlUsAEszwKWPym9fgdO1kEANDcqg4f8R49XPxy7DaXUdSFF6Xu2EZTSyt6WyobZcRUnysOsdNApd+h9i98TW9uOa3haWU3H2OFUmxz/hKYxOP5clGZ1z3fVvqKFnUGsdICcNqLIKWKmYXGCOgzLHIWX5In+Khh/FtkgIUyxeNOwUFLGM8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
